name: ethereum
summary: An Ethereum framework for Snappy Ubuntu
description: A framework providing all the essentials needed in order to develop for and interact with the Ethereum blockchain
vendor: Lefteris <lefteris@refu.co>
architectures: [amd64, armhf]
icon: ethereum_icon.png
version: 0.1.4
type: framework
framework-policy: framework-policy/
config: bin/configurator

parts:
  geth:
    plugin: x-script
    script: scripts/build_geth.sh
    destination-dir: bin

  files-to-copy:
    plugin: copy
    files:
      scripts/geth_selector.sh: bin/geth
      config/configurator.py: bin/configurator
      config/default_config.yaml: config/default_config.yaml

  configurator:
    plugin: python2
    python-packages:
      - PyYAML

services:

  geth:
    start: ./bin/geth
    description: "The Go Ethereum client"
    # network-admin is needed for the ifconfig command inside selector script
    # if we end up not using it network-admin can go
    caps:
      - network-client
      - network-service
      - network-admin
