name: ethereum
summary: An Ethereum framework for Snappy Ubuntu
description: A framework providing all the essentials needed in order to develop for and interact with the Ethereum blockchain
vendor: Lefteris <lefteris@refu.co>
architectures: [amd64, armhf]
icon: icon.png
version: 0.1
type: framework
framework-policy: framework-policy/

parts:
  geth:
    plugin: x-script
    script: scripts/build_geth.sh
    destination-dir: bin

  files-to-copy:
    plugin: copy
    files:
      scripts/geth_selector.sh: bin/geth
      

services:

  geth:
    start: ./bin/geth
    description: "The Go Ethereum client"
    caps:
      - network-client
      - network-service
      - network-admin
