name: ethereum
vendor: Lefteris <lefteris@refu.co>
architectures: [amd64, armhf]
version: 0.1
type: framework
services:

- name: geth
  start: ./bin/geth
  description: "The Go Ethereum client"
  caps:
    - network-client
    - network-service
    - network-admin
